FROM python:3.9-slim

COPY requirements.txt requirements.txt
COPY api/client_api.py app/client_api.py

RUN pip install --no-cache-dir -r requirements.txt

WORKDIR /app

CMD ["uvicorn", "client_api:app", "--host", "0.0.0.0", "--port", "8887"]
